training_env: "minigrid"
model_config_name: "mlp"

accelerator: "cpu"
precision: "16-mixed"
max_steps: 20_000

learning_rate: 0.0001
batch_size: 256

use_double_dqn: True
epsilon_upper: 0.60
epsilon_lower: 0.01
epsilon_decay_steps: 10_000

buffer_capacity: 64_000
collect_data_num_parallel_envs: 10
collect_data_every_n_steps: 250
collect_data_num_steps_in_each_env: 3200

valid_num_parallel_envs: 10
val_check_interval: 1000
