max_steps: -1
accelerator: "cuda"
precision: "16-mixed"

optimizer_class: "AdamW"
learning_rate: 0.0001
batch_size: 128

hidden_dim: 512
num_blocks: 5

importance_sampling_clip_range: [0.8, 1.2]

buffer_capacity: 128000
collect_data_num_parallel_envs: 10
collect_data_every_n_updates: 10
collect_data_num_steps: 256

val_check_interval: 5000
valid_num_runs: 50
valid_num_parallel_envs: 10

hardcore: False

use_early_stopping: False
early_stopping_threshold: None
early_stopping_patience: 5
early_stopping_min_delta: 0.0
